language: php

php:
 - 7.2
 - 7.3
 - 7.4

before_script:
 - composer install --prefer-dist

script:
 - ./vendor/bin/phpstan analyze --no-progress
 - ./tests/run-tests.sh

cache:
 directories:
  - vendor

notifications:
 email: false
